import { RelayEnvironmentProvider } from "react-relay";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { getCurrentEnvironment } from "@/relay/environment";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const environment = getCurrentEnvironment();

  return (
    <html lang="en">
      <RelayEnvironmentProvider environment={environment}>
        <body className={inter.className}>{children}</body>
      </RelayEnvironmentProvider>
    </html>
  );
}
